config/routes.rb
Rails.application.routes.draw do
  
  resources :bypass_password_instances
  resources :bags
  resources :saved_lists
  get 'session/new', to: 'sessions#new'
  post 'session/new', to: 'sessions#create'
  get 'session/new/:key', to: 'sessions#bypass_password'
  get 'session/twitter/:id', to: 'sessions#createTwitterSession', as: 'twitter_session'
  delete 'session', to: 'sessions#destroy'
  
  get '/session/forgot_password', to: 'sessions#show_forgot_password', as: 'forgot_password_session'
  post '/session/forgot_password', to: 'sessions#forgot_password'
  
 get '/subscribe/:emailDest', to: 'mailtest#toggle_sub', as: 'subscribe_newsletter'
  
  get '/user/change_password', to: 'users#edit_password', as: 'change_password'
  post '/user/change_password', to: 'users#update_password', as: 'update_password'
  
  get 'items/:id', to: 'items#show', as: 'show_item'
  get 'get_image/:id', to: 'items#getImage', as: 'get_image'


  get '/search' => 'pages#search', :as => 'search_page'
  post '/profile' => 'profile#profilepageEmail', :as => 'profilepage'
  get '/profile' => 'profile#profilepage'
  
  
  post '/newsletter' => 'mailtest#mailtest', :as => 'mailtestPOST'
  get '/newsletter' => 'mailtest#mail_show', :as => 'mailtest'
  
  get '/scan' => 'pages#cam_scan', as: 'cam_scan'

  get '/admin' => 'pages#admin_portal'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :users, only: %i[new create]
  resources :session, only: %i[new create destroy]
  resources :subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items
  
  

  root 'homepage#show'
  get '/collection/:col', to: 'pages#collections', as: 'show_collections'
  get '/collection/:col/:fil', to: 'pages#collections', as: 'show_filtered'
  
  get '/HelpAndSupport', to: 'homepage#helpAndSupp', as: 'help_and_support'
 
  post '/toBag/:id', to: 'bag_items#addToList', as: 'add_to_bag'
  post '/removeB/:id', to: 'bag_items#removeFromList', as: 'remv_from_bag'
  
  
  post '/addOrRemoveFromSL/:id', to:'saved_lists#toggleList', as: 'toggle_item_saved_list'
  
  post '/checkout/:id', to: 'bags#checkout', as: 'checkout_bag'
  
  get '/saved_list/:id', to: 'saved_lists#show', as: 'show_user_saved_list'
  get '/bag/:id', to: 'bags#show', as: 'show_user_bag'
  get '/bag/:id/:rating', to: 'bags#show', as: 'show_user_bag_rating'
  
  get "/auth/twitter/callback", to: 'omniauth_callbacks#twitter'
  
  post '/rate', to: 'ratings#addRating', as: 'add_rating_path'
  
  resources :bag_items
end

app/models/bag.rb
class Bag < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_many :bag_items
  has_many :items, through: :bag_items
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  before_action :set_bag, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token
  # GET /bags or /bags.json
  def index
    @bags = Bag.all
  end

  # GET /bags/1 or /bags/1.json
  def show
    if !params[:rating].nil?
      @showRating = true
    else
      @showRating = false
    end
    
    @total_items = 0;
    @uniq_items = 0;
    @items = @bag.items
    @price = 0.00
    @bag_items = @bag.bag_items

    @bag_items.each do |i|
      item = Item.find(i.item_id)
      @price = @price + i.quantity * item.price
      @total_items = @total_items + i.quantity
      @uniq_items = @uniq_items + 1
    end
  end

  # GET /bags/new
  def new
    @bag = Bag.new
  end

  # GET /bags/1/edit
  def edit
  end
  
  def checkout
    
    user = current_user
    mBag = user.bag
    
    if !mBag.items.empty?
    
      mBag.items.each do |item|
        item.update(purchase_count: item.purchase_count + 1)
        item.save
      end
      mBag.items.delete_all
      
      if user.first_checkout
        showRating = true
        user.update(first_checkout: 0)
        user.save
      else
        showRating = false
      end
      
      
      if showRating
        redirect_to show_user_bag_rating_path(:id => current_user.id, :rating => "rate")
      else
        redirect_to show_user_bag_path(:id => current_user.id)
      end
    else
      redirect_to show_user_bag_path(:id => current_user.id), notice: "You need to have something in your cart to checkout!"
    end
  end
  
  # POST /bags or /bags.json
  def create
    @bag = Bag.new(bag_params)

    respond_to do |format|
      if @bag.save
        format.html { redirect_to @bag, notice: "Bag was successfully created." }
        format.json { render :show, status: :created, location: @bag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bags/1 or /bags/1.json
  def update
    respond_to do |format|
      if @bag.update(bag_params)
        format.html { redirect_to @bag, notice: "Saved list was successfully updated." }
        format.json { render :show, status: :ok, location: @bag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bags/1 or /bags/1.json
  def destroy
    @bag.destroy
    respond_to do |format|
      format.html { redirect_to bags_url, notice: "Saved list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bag
      user = User.find_by(id: params[:id])
      @bag = user.bag
    end

    # Only allow a list of trusted parameters through.
    def bag_params
      params.require(:bag).permit(:user_id)
    end
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/views/bags/_form.html.erb
<%= form_with(model: bag, local: true) do |form| %>
  <% if bag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bag.errors.count, "error") %> prohibited this bag from being saved:</h2>

      <ul>
      <% bag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bags/edit.html.erb
<h1>Editing Bag</h1>

<%= render 'form', bag: @bag %>

<%= link_to 'Show', @bag %> |
<%= link_to 'Back', bags_path %>

app/views/bags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bags</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bags.each do |bag| %>
      <tr>
        <td><%= link_to 'Show', bag %></td>
        <td><%= link_to 'Edit', edit_bag_path(bag) %></td>
        <td><%= link_to 'Destroy', bag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bag', new_bag_path %>

app/views/bags/new.html.erb
<h1>New Bag</h1>

<%= render 'form', bag: @bag %>

<%= link_to 'Back', bags_path %>

app/views/bags/show.html.erb
<p>You currently have <%=@total_items%> total items and <%=@uniq_items%> types of items.</p>


<%if !@items.nil?%>
        <h1>Your bag</h1>
        <% @items.each do |item| %>
            <% @bag_items.each do |bag_item| %>
                <div class = "card">
                    <%= link_to item.name, show_item_path(:id => item.id), method: :get %>
                    <small>$<%=item.price%> <br> <%=item.description%> <br>
                    Size: <%=bag_item.size%> <br> Color: <%=bag_item.color%> <br>
                    Quantity: <%=bag_item.quantity%></small>
                    
                    <div class = "image-button-container">
                        <%= link_to(image_tag(item.image, width: 200), show_item_path(:id => item.id)) %>
                        <div class = "float-btn">
                            <%= button_to toggle_item_saved_list_path(:id => item.id), method: :post do %>
                            <%if logged_in? %>
                                <%if @savedListItems.include? item %>
                                    <%= image_tag "https://cdn2.iconfinder.com/data/icons/peppyicons/512/heart-512.png", class: "float-img"%>
                                <%else%>
                                    <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                                <%end%>
                            <%else%>
                                <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                            <%end%>
                        <%end%>
                        </div>
                    </div>
                    <%= link_to 'Remove from bag', remv_from_bag_path(:id => item.id), method: :post %>
                </div>
            <%end%>
        <%end%>
        
        <form action=<%= checkout_bag_path(:id => current_user.id) %> method = "post">
            <input type="submit" value="Checkout" />
        </form>
<%end%>

<h2><bold>Price: $<%= @price %></bold></h2>


<%if @showRating %>
<h1></h1>
  <script>window.onload = () => {
    document.querySelector('[data-target="#exampleModal"]').click();
  }</script>


  <div class="container py-3">
  
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Reopen Rating Popup
    </button>
  
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Hey, thanks for shopping at Clothic!
            <br> <br> Looks like it's you first time here, please consider rating your experience!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <%= form_with url: logged_in? ? add_rating_path_url : new_session_path, method: :post do |f| %>
                <%= radio_button_tag(:likert, 0) %>
                <%= label_tag(:likert, "0") %>
                <%= radio_button_tag(:likert, 1) %>
                <%= label_tag(:likert, "1") %>
                <%= radio_button_tag(:likert, 2) %>
                <%= label_tag(:likert, "2") %>
                <%= radio_button_tag(:likert, 3) %>
                <%= label_tag(:likert, "3") %>
                <%= radio_button_tag(:likert, 4) %>
                <%= label_tag(:likert, "4") %>
                <%= radio_button_tag(:likert, 5) %>
                <%= label_tag(:likert, "5") %>
                
                <%= f.submit "Submit Rating" %>
              <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  
  </div>
<%end%>


<br><br><br><br>

<h2 id="notice"><%= notice %></h2>