config/routes.rb
Rails.application.routes.draw do
  
  resources :bypass_password_instances
  resources :bags
  resources :saved_lists
  get 'session/new', to: 'sessions#new'
  post 'session/new', to: 'sessions#create'
  get 'session/new/:key', to: 'sessions#bypass_password'
  get 'session/twitter/:id', to: 'sessions#createTwitterSession', as: 'twitter_session'
  delete 'session', to: 'sessions#destroy'
  
  get '/session/forgot_password', to: 'sessions#show_forgot_password', as: 'forgot_password_session'
  post '/session/forgot_password', to: 'sessions#forgot_password'
  
 get '/subscribe/:emailDest', to: 'mailtest#toggle_sub', as: 'subscribe_newsletter'
  
  get '/user/change_password', to: 'users#edit_password', as: 'change_password'
  post '/user/change_password', to: 'users#update_password', as: 'update_password'
  
  get 'items/:id', to: 'items#show', as: 'show_item'
  get 'get_image/:id', to: 'items#getImage', as: 'get_image'


  get '/search' => 'pages#search', :as => 'search_page'
  post '/profile' => 'profile#profilepageEmail', :as => 'profilepage'
  get '/profile' => 'profile#profilepage'
  
  
  post '/newsletter' => 'mailtest#mailtest', :as => 'mailtestPOST'
  get '/newsletter' => 'mailtest#mail_show', :as => 'mailtest'
  
  get '/scan' => 'pages#cam_scan', as: 'cam_scan'

  get '/admin' => 'pages#admin_portal'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :users, only: %i[new create]
  resources :session, only: %i[new create destroy]
  resources :subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items
  
  

  root 'homepage#show'
  get '/collection/:col', to: 'pages#collections', as: 'show_collections'
  get '/collection/:col/:fil', to: 'pages#collections', as: 'show_filtered'
  
  get '/HelpAndSupport', to: 'homepage#helpAndSupp', as: 'help_and_support'
 
  post '/toBag/:id', to: 'bag_items#addToList', as: 'add_to_bag'
  post '/removeB/:id', to: 'bag_items#removeFromList', as: 'remv_from_bag'
  
  
  post '/addOrRemoveFromSL/:id', to:'saved_lists#toggleList', as: 'toggle_item_saved_list'
  
  post '/checkout/:id', to: 'bags#checkout', as: 'checkout_bag'
  
  get '/saved_list/:id', to: 'saved_lists#show', as: 'show_user_saved_list'
  get '/bag/:id', to: 'bags#show', as: 'show_user_bag'
  get '/bag/:id/:rating', to: 'bags#show', as: 'show_user_bag_rating'
  
  get "/auth/twitter/callback", to: 'omniauth_callbacks#twitter'
  
  post '/rate', to: 'ratings#addRating', as: 'add_rating_path'
  
  resources :bag_items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  
  has_and_belongs_to_many :saved_list
  has_many :bag_items
  has_many :bags, through: :bags_items
    def display
        self.image
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end
  
  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end
  
  def getImage
    return Item.find(params[:id]).image
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:price, :name, :description, :image, :popularity, :collection)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :item_image %>
  </div>

  <div class="field">
    <%= form.label :popularity %>
    <%= form.text_field :popularity, id: :item_popularity %>
  </div>

  <div class="field">
    <%= form.label :collection %>
    <%= form.text_field :collection, id: :item_collection %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
<<<<<<< HEAD
      <th>Price</th>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Popularity</th>
      <th>Collection</th>
=======
>>>>>>> 0fa55d26c19cc9f18940f17690863f2ac885da78
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.price %></td>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.image %></td>
        <td><%= item.popularity %></td>
        <td><%= item.collection %></td>

        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div id="demo" class="carousel slide" data-ride="carousel">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  
  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag(@item.image, width: 1100, height: 500, alt: "Image 1") %>
     
    </div>
    <div class="carousel-item">
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Ruby_logo.svg/1024px-Ruby_logo.svg.jpg" alt="Image 2" width="1100" height="500">
    </div>
    <div class="carousel-item">
      <img src="https://upload.wikimedia.org/wikipedia/commons/1/16/Ruby_on_Rails-logo.jpg" alt="Image 3" width="1100" height="500">
    </div>
  </div>
  
  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

<h2>
  <strong>Price: $</strong>
  <%= @item.price %>
</h2>

<h2>
  <strong>Name:</strong>
  <%= @item.name %>
</h2>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>


<p>
  <strong>Popularity:</strong>
  <%= @item.popularity %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @item.collection %>
</p>


<%= form_with url: logged_in? ? add_to_bag_path(:id => @item.id) : new_session_path, method: :post do |f| %>
<p>
    <b>Size</b><br />
    <%if @item.small %>
      <%= f.radio_button :size, 'Small' %> Small<br />
    <%else%>
      <p>We don't make this item in this small or it is out of stock at this size.</p>
    <%end%>
    <%if @item.medium %>
      <%= f.radio_button :size, 'Medium' %> Medium<br />
    <%else%>
      <p>We don't make this item in this medium or it is out of stock at this size.</p>
    <%end%>
    <%if @item.large %>
      <%= f.radio_button :size, 'Large' %> Large<br />
    <%else%>
      <p>We don't make this item in this large or it is out of stock at this size.</p>
    <%end%>
</p>

<p>
    <b>Color</b><br />
    <%if @item.color1 %>
      <%= f.radio_button :color, @item.color1 %> <%= @item.color1 %><br />
    <%end%>
    <%if @item.color2 %>
      <%= f.radio_button :color, @item.color2 %> <%= @item.color2 %><br />
    <%end%>
    <%if @item.color3 %>
      <%= f.radio_button :color, @item.color3 %> <%= @item.color3 %><br />
    <%end%>
</p>
<p>
    <b>Quantity</b><br />
    <%= f.select :quantity, options_for_select(1..10) %>
</p>
  
  <%= f.submit "Add to bag" %>

<% end %>

<h2 id="notice"><%= notice %></h2>

<br><br>