config/routes.rb
Rails.application.routes.draw do
  
  resources :bypass_password_instances
  resources :bags
  resources :saved_lists
  get 'session/new', to: 'sessions#new'
  post 'session/new', to: 'sessions#create'
  get 'session/new/:key', to: 'sessions#bypass_password'
  get 'session/twitter/:id', to: 'sessions#createTwitterSession', as: 'twitter_session'
  delete 'session', to: 'sessions#destroy'
  
  get '/session/forgot_password', to: 'sessions#show_forgot_password', as: 'forgot_password_session'
  post '/session/forgot_password', to: 'sessions#forgot_password'
  
 get '/subscribe/:emailDest', to: 'mailtest#toggle_sub', as: 'subscribe_newsletter'
  
  get '/user/change_password', to: 'users#edit_password', as: 'change_password'
  post '/user/change_password', to: 'users#update_password', as: 'update_password'
  
  get 'items/:id', to: 'items#show', as: 'show_item'
  get 'get_image/:id', to: 'items#getImage', as: 'get_image'


  get '/search' => 'pages#search', :as => 'search_page'
  post '/profile' => 'profile#profilepageEmail', :as => 'profilepage'
  get '/profile' => 'profile#profilepage'
  
  
  post '/newsletter' => 'mailtest#mailtest', :as => 'mailtestPOST'
  get '/newsletter' => 'mailtest#mail_show', :as => 'mailtest'
  
  get '/scan' => 'pages#cam_scan', as: 'cam_scan'

  get '/admin' => 'pages#admin_portal'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :users, only: %i[new create]
  resources :session, only: %i[new create destroy]
  resources :subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items
  
  

  root 'homepage#show'
  get '/collection/:col', to: 'pages#collections', as: 'show_collections'
  get '/collection/:col/:fil', to: 'pages#collections', as: 'show_filtered'
  
  get '/HelpAndSupport', to: 'homepage#helpAndSupp', as: 'help_and_support'
 
  post '/toBag/:id', to: 'bag_items#addToList', as: 'add_to_bag'
  post '/removeB/:id', to: 'bag_items#removeFromList', as: 'remv_from_bag'
  
  
  post '/addOrRemoveFromSL/:id', to:'saved_lists#toggleList', as: 'toggle_item_saved_list'
  
  post '/checkout/:id', to: 'bags#checkout', as: 'checkout_bag'
  
  get '/saved_list/:id', to: 'saved_lists#show', as: 'show_user_saved_list'
  get '/bag/:id', to: 'bags#show', as: 'show_user_bag'
  get '/bag/:id/:rating', to: 'bags#show', as: 'show_user_bag_rating'
  
  get "/auth/twitter/callback", to: 'omniauth_callbacks#twitter'
  
  post '/rate', to: 'ratings#addRating', as: 'add_rating_path'
  
  resources :bag_items
end

app/models/saved_list.rb
class SavedList < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_and_belongs_to_many :items
  
end

app/controllers/saved_lists_controller.rb
class SavedListsController < ApplicationController
  before_action :set_saved_list, only: %i[ show edit update destroy ]

  # GET /saved_lists or /saved_lists.json
  def index
    @saved_lists = SavedList.all
  end

  # GET /saved_lists/1 or /saved_lists/1.json
  def show
    if current_user 
      @items = @saved_list.items
    else
      redirect_to new_session_path
    end
  end

  # GET /saved_lists/new
  def new
    @saved_list = SavedList.new
  end

  # GET /saved_lists/1/edit
  def edit
  end
  
  def toggleList
    if current_user
      item = Item.find_by(id: params[:id])
      savedList = current_user.saved_list
      if !savedList.items.include? item
        item.update(sl_count: item.sl_count + 1)
        item.save
        addToList(params[:id])
        redirect_back(fallback_location: root_path)
      else
        item.update(sl_count: item.sl_count - 1)
        item.save
        removeFromList(params[:id])
         redirect_back(fallback_location: root_path)
      end
    else
      redirect_to new_session_path
    end
  end
  
  # POST /saved_lists or /saved_lists.json
  def create
    @saved_list = SavedList.new(saved_list_params)

    respond_to do |format|
      if @saved_list.save
        format.html { redirect_to @saved_list, notice: "Saved list was successfully created." }
        format.json { render :show, status: :created, location: @saved_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @saved_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saved_lists/1 or /saved_lists/1.json
  def update
    respond_to do |format|
      if @saved_list.update(saved_list_params)
        format.html { redirect_to @saved_list, notice: "Saved list was successfully updated." }
        format.json { render :show, status: :ok, location: @saved_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @saved_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saved_lists/1 or /saved_lists/1.json
  def destroy
    @saved_list.destroy
    respond_to do |format|
      format.html { redirect_to saved_lists_url, notice: "Saved list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saved_list
      user = User.find_by(id: params[:id])
      @saved_list = user.saved_list
    end
  
    # Only allow a list of trusted parameters through.
    def saved_list_params
      params.require(:saved_list).permit(:user_id)
    end
    
    def addToList(item_id)
      item = Item.find_by(id: item_id)
      user = current_user
      savedList = user.saved_list
      savedList.items << item unless savedList.items.include?(item)
      
      #add 1 to the popularity value
      if savedList.items.include?(item)
        currentPop = item.popularity
        item.popularity = currentPop + 1
        item.save
      end
    end
  
    def removeFromList(item_id)
      item = Item.find_by(id: item_id)
      user = current_user
      savedList = user.saved_list
      savedList.items.destroy(item)
      
      currentPop = item.popularity
      item.popularity = currentPop - 1
      item.save
    end
end

app/helpers/saved_lists_helper.rb
module SavedListsHelper
end

app/views/saved_lists/_form.html.erb
<%= form_with(model: saved_list, local: true) do |form| %>
  <% if saved_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saved_list.errors.count, "error") %> prohibited this saved_list from being saved:</h2>

      <ul>
      <% saved_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/saved_lists/edit.html.erb
<h1>Editing Saved List</h1>

<%= render 'form', saved_list: @saved_list %>

<%= link_to 'Show', @saved_list %> |
<%= link_to 'Back', saved_lists_path %>

app/views/saved_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Saved Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saved_lists.each do |saved_list| %>
      <tr>
        <td><%= link_to 'Show', saved_list %></td>
        <td><%= link_to 'Edit', edit_saved_list_path(saved_list) %></td>
        <td><%= link_to 'Destroy', saved_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saved List', new_saved_list_path %>

app/views/saved_lists/new.html.erb
<h1>New Saved List</h1>

<%= render 'form', saved_list: @saved_list %>

<%= link_to 'Back', saved_lists_path %>

app/views/saved_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Saved List</h1>
<%if !@items.nil? && @items.length != 0%>
        <% @items.each do |item| %>
            <div class = "card">
                <%= link_to item.name, show_item_path(:id => item.id), method: :get %>
                <small>$<%=item.price%> <br> <%=item.description%></small></p>
                
                <div class = "image-button-container">
                    <%= link_to(image_tag(item.image, width: 200), show_item_path(:id => item.id)) %>
                    <div class = "float-btn">
                        <%= button_to toggle_item_saved_list_path(:id => item.id), method: :post do %>
                            <%if logged_in? %>
                                <%if @savedListItems.include? item %>
                                    <%= image_tag "https://cdn2.iconfinder.com/data/icons/peppyicons/512/heart-512.png", class: "float-img"%>
                                <%else%>
                                    <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                                <%end%>
                            <%else%>
                                <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                            <%end%>
                        <%end%>
                    </div>
                </div>
            </div>
            
        <%end%>
<%else%>
<p>Nothing in saved list.</p>
<%end%>