config/routes.rb
Rails.application.routes.draw do
  
  resources :bypass_password_instances
  resources :bags
  resources :saved_lists
  get 'session/new', to: 'sessions#new'
  post 'session/new', to: 'sessions#create'
  get 'session/new/:key', to: 'sessions#bypass_password'
  get 'session/twitter/:id', to: 'sessions#createTwitterSession', as: 'twitter_session'
  delete 'session', to: 'sessions#destroy'
  
  get '/session/forgot_password', to: 'sessions#show_forgot_password', as: 'forgot_password_session'
  post '/session/forgot_password', to: 'sessions#forgot_password'
  
 get '/subscribe/:emailDest', to: 'mailtest#toggle_sub', as: 'subscribe_newsletter'
  
  get '/user/change_password', to: 'users#edit_password', as: 'change_password'
  post '/user/change_password', to: 'users#update_password', as: 'update_password'
  
  get 'items/:id', to: 'items#show', as: 'show_item'
  get 'get_image/:id', to: 'items#getImage', as: 'get_image'


  get '/search' => 'pages#search', :as => 'search_page'
  post '/profile' => 'profile#profilepageEmail', :as => 'profilepage'
  get '/profile' => 'profile#profilepage'
  
  
  post '/newsletter' => 'mailtest#mailtest', :as => 'mailtestPOST'
  get '/newsletter' => 'mailtest#mail_show', :as => 'mailtest'
  
  get '/scan' => 'pages#cam_scan', as: 'cam_scan'

  get '/admin' => 'pages#admin_portal'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :items
  resources :users, only: %i[new create]
  resources :session, only: %i[new create destroy]
  resources :subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :items
  
  

  root 'homepage#show'
  get '/collection/:col', to: 'pages#collections', as: 'show_collections'
  get '/collection/:col/:fil', to: 'pages#collections', as: 'show_filtered'
  
  get '/HelpAndSupport', to: 'homepage#helpAndSupp', as: 'help_and_support'
 
  post '/toBag/:id', to: 'bag_items#addToList', as: 'add_to_bag'
  post '/removeB/:id', to: 'bag_items#removeFromList', as: 'remv_from_bag'
  
  
  post '/addOrRemoveFromSL/:id', to:'saved_lists#toggleList', as: 'toggle_item_saved_list'
  
  post '/checkout/:id', to: 'bags#checkout', as: 'checkout_bag'
  
  get '/saved_list/:id', to: 'saved_lists#show', as: 'show_user_saved_list'
  get '/bag/:id', to: 'bags#show', as: 'show_user_bag'
  get '/bag/:id/:rating', to: 'bags#show', as: 'show_user_bag_rating'
  
  get "/auth/twitter/callback", to: 'omniauth_callbacks#twitter'
  
  post '/rate', to: 'ratings#addRating', as: 'add_rating_path'
  
  resources :bag_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bag.rb
class Bag < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_many :bag_items
  has_many :items, through: :bag_items
end

app/models/bag_item.rb
class BagItem < ApplicationRecord
  validates :bag_id, presence: true
  validates :item_id, presence: true
  validates :color, presence: true
  validates :size, presence: true
  validates :quantity, presence: true
  belongs_to :bag
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  
  has_and_belongs_to_many :saved_list
  has_many :bag_items
  has_many :bags, through: :bags_items
    def display
        self.image
    end

end

app/models/rating.rb
class Rating < ApplicationRecord
  validates :user_id, presence: true
end

app/models/saved_list.rb
class SavedList < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  has_and_belongs_to_many :items
  
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :email, presence: true, format: { with: /\A\S+@.+\.\S+\z/, message: "please enter email with format: [string]@[string].[string]"} , uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
 validates :email, presence: true, format: { with: /\A\S+@.+\.\S+\z/, message: "please enter email with format: [string]@[string].[string]"} , uniqueness: true
 validates :password, length: {in: 8..20, wrong_length: "Passwords need to be within 8 and 20 characters"}, confirmation: true

 
    has_one :saved_list
    has_one :bag
    def authenticate(password)
        self.password == password
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mailtest_helper.rb
module MailtestHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <p>
        <div class="input-group-btn">  
            <%= button_to "Home".html_safe, root_path, class: "btn btn-info glyphicon glyphicon-home", method: :get%>
        </div>
        <div class="input-group-btn">  
            <%= button_to "Scan".html_safe, cam_scan_path, class: "btn btn-info glyphicon glyphicon-qrcode", method: :get%>
        </div>
        <% if logged_in? %>
                <div class="input-group-btn">  
                <%= button_to "Saved".html_safe, show_user_saved_list_path(:id => current_user.id), class: "btn btn-info glyphicon glyphicon-list", method: :get%>
                </div>
                <div class="input-group-btn">  
                    <%= button_to "Profile".html_safe, profilepage_url, class: "btn btn-info glyphicon glyphicon-user", method: :get%>
                </div>
          
        <% else %>
                <div class="input-group-btn">  
                    <%= button_to "Saved".html_safe, new_session_path, class: "btn btn-info glyphicon glyphicon-list", method: :get%>
                </div>
                <div class="input-group-btn">  
                    <%= button_to "Profile".html_safe, new_session_path, class: "btn btn-info glyphicon glyphicon-user", method: :get%>
                </div>
              
        <% end %>
    </p>
    
    
        
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Clothic App', root_path, class:"navbar-brand" %>
      <% if logged_in? %>
        <div class="hello-user"><%= "Hello #{current_user.name}!"%></div>
        <%= link_to 'Logout', session_path, method: :delete %>
        <%= link_to(image_tag("https://img.icons8.com/ios/452/shopping-bag--v1.png", class: 'image-responsive'), show_user_bag_path(:id => current_user.id),  :method => :get) %>
      <% else %>
        <%= link_to 'Log In', new_session_path %>
        <%= link_to(image_tag("https://img.icons8.com/ios/452/shopping-bag--v1.png", class: 'image-responsive'), new_session_path,  :method => :get) %>
      <% end %>
      
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          <%= link_to 'New Arrivals', show_collections_path(:col =>'New Arrivals'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Womens', show_collections_path(:col =>'Womens'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Mens', show_collections_path(:col =>'Mens'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Kids', show_collections_path(:col =>'Kids'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Help & Support', help_and_support_path, class:"nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Saved List', show_user_saved_list_path(:id => current_user.id), class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Shopping bag', show_user_bag_path(:id => current_user.id), class:"nav-link" %>
          </li>
          
        <% else %>
           <li class="nav-item">
            <%= link_to 'Saved List', new_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Shopping bag', new_session_path, class:"nav-link" %>
          </li>
          
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
        <%= form_tag(search_page_path, :method => "get",   
          class: 'navbar-form navbar-left') do %>  
            <div class="input-group">  
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
            <div class="input-group-btn">  
              <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
            </div>  
          </div>  
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <title>Clothic App</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 100%;
    height: 20%;
  }
  </style
  </head>
  <body>
    <%= render 'layouts/header' %>
    
  
    <div class = "container">
      </br>
      <%= yield %>
      <br><br><br><br><br><br><br><br>
      <br><br><br><br><br>
      <p>Created using Ruby on Rails 5 by: Jeffrey Tan (S3851781) and William Hu (S3856557) </p>
      <br><br><br><br>
      
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/admin_portal.html.erb
<%if current_user %>

<%if current_user.is_admin %>

<h1> Admin Portal </h1>
<br><br>

<h2>Saved Items Summary</h2>
<% @sLCountOrderItems.each do |item| %>
<p> <b>Item name:</b> <%= item.name %> <br><b>Number in saved lists:</b> <%= item.sl_count %></p>
<%end%>

<h2>Purchased Items Summary</h2>
<% @pCountOrderItems.each do |item| %>
<p><b>Item name:</b> <%= item.name %> <br><b>Number purchased:</b> <%= item.purchase_count %></p>
<%end%>


<h2>Customer Ratings Summary</h2>
<p>Average customer ratings is: <%= @avg_rating %></p>


<h2>Newsletter Subscriptions</h2>
<% @subscriptions.each do |subscription| %>
<p>Email: <%=subscription.email%></p> <br>
<%end%>

<%else%>
<h1>Sorry, this portal is admins only.</h1>
<%end%>

<%else%>

<h1>Please go back to the homepage</h1>

<%end%>

app/views/pages/cam_scan.html.erb
<h1> Scan your image:</h1>


<script>function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#cam-img')
                    .attr('src', e.target.result)
                    .width(400)
                    .height(200);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }</script>

<body>
  <input type='file' onchange="readURL(this);" />
    <img id="cam-img" src="#" alt="Scan your image" />

</body>

app/views/pages/collections.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<%# To render a collection %>
<%if !@items.nil?%>
<p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Filters
  </a>
</p>
<div class="collapse" id="collapseExample">
    <div class="card card-body">
        
        <%= form_tag(show_filtered_path(:col => @collection, :fil => "filtered"), method: "get") do |f| %>
            <p>
                <%= submit_tag("All", name: 'all_filter_button') %> <br> <br>
                <b>Size</b><br />
                 
                  <%= radio_button_tag(:size, "Small") %>
                  <%= label_tag(:size, "Small") %>
                  <%= radio_button_tag(:size, "Medium") %>
                  <%= label_tag(:size, "Medium") %>
                  <%= radio_button_tag(:size, "Large") %>
                  <%= label_tag(:size, "Large") %>
            </p>
            
            <p>
                <b>Color</b><br />
                    <input type="checkbox" id="red" name="red" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:red, "Red") %>
        			<input type="checkbox" id="blue" name="blue" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:blue, "Blue") %>
        			<input type="checkbox" id="black" name="black" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:black, "Black") %>
        			<input type="checkbox" id="yellow" name="yellow" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:yellow, "Yellow") %>
        			<input type="checkbox" id="green" name="green" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:green, "Green") %>
        			<input type="checkbox" id="grey" name="grey" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			 <%= label_tag(:grey, "Grey") %>
        			<input type="checkbox" id="white" name="white" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:white, "White") %>
        			<input type="checkbox" id="pink" name="pink" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			 <%= label_tag(:pink, "Pink") %>
        			<input type="checkbox" id="denim" name="denim" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			 <%= label_tag(:denim, "Denim") %>
        			<input type="checkbox" id="leather" name="leather" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:leather, "Leather") %>
            </p>
            
            <p>
                <b>Tags</b><br />
                    <input type="checkbox" id="stylish" name="stylish" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:stylish, "Stylish") %>
        			<input type="checkbox" id="winter" name="winter" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:winter, "Winter") %>
        			<input type="checkbox" id="casual" name="casual" value="1" <%if @tickAll %> checked=“checked” <%end%> />
        			<%= label_tag(:casual, "Casual") %>
            </p>
              
              <%= submit_tag("Apply Filters") %>
              
            
        <% end %>
        
        
    </div>
</div>


    
        <h1><%=@collection%></h1>
        <p>Total number of items: <%=@collection.size %></p>
        <% @items.each do |item| %>
            <div class = "card">
                <%= link_to item.name, show_item_path(:id => item.id), method: :get %>
                <small>$<%=item.price%> <br> <%=item.description%></small>
                
                <div class = "image-button-container">
                    <%= link_to(image_tag(item.image, width: 200), show_item_path(:id => item.id)) %>
                    <div class = "float-btn">
                        <%= button_to toggle_item_saved_list_path(:id => item.id), method: :post do %>
                            <%if logged_in? %>
                                <%if @savedListItems.include? item %>
                                    <%= image_tag "https://cdn2.iconfinder.com/data/icons/peppyicons/512/heart-512.png", class: "float-img"%>
                                <%else%>
                                    <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                                <%end%>
                            <%else%>
                                <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                            <%end%>
                        <%end%>
                    </div>
                </div>
            </div>
        <%end%>
        
<%end%>

<%if @items.count == 0 %>
<br><br><br>
<h2>Nothing matching your filters</h2>
<%end%>

app/views/pages/search.html.erb
<h3>Search Result</h3>  

    <% @results.each do |result| %>  
        <div class = "card">
                <%= link_to result.name, show_item_path(:id => result.id), method: :get %>
                <small>$<%=result.price%> <br> <%=result.description%></small>
                
                <div class = "image-button-container">
                    <%= link_to(image_tag(result.image, width: 200), show_item_path(:id => result.id)) %>
                    <div class = "float-btn">
                        <%= button_to toggle_item_saved_list_path(:id => result.id), method: :post do %>
                            <%if logged_in? %>
                                <%if @savedListItems.include? result %>
                                    <%= image_tag "https://cdn2.iconfinder.com/data/icons/peppyicons/512/heart-512.png", class: "float-img"%>
                                <%else%>
                                    <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                                <%end%>
                            <%else%>
                                <%= image_tag "https://cdn0.iconfinder.com/data/icons/thin-voting-awards/57/thin-233_heart_favorite_like-512.png", class: "float-img"%>
                            <%end%>
                        <%end%>
                    </div>
                </div>
            </div>
    <% end %>